spring.application.name=ai-code-review-backend
spring.profiles.active=dev
server.port=8081

jwt.secret=aVeryLongSecretKeyForAiCodeReviewAssistantProject2026MustBeAtLeast32Bytes
jwt.expiration=86400000